### ISSUE TITLE
Unclear install instructions

### ISSUE THREAD

**Issue by digitalight** [dracula/geany#2]
On https://draculatheme.com/geany
Instructions for installation say:

> Download using the GitHub .zip download option

Inside the zip file the readme.md file says:
All instructions can be found at draculatheme.com/geany.

Therefore no clear instructions for installation. Just a loop.

Can some instruction on how to install into Geany be created to help new users.

**Comment by digitalight** [comment]
Thanks @RaphGL. Looked at your commit and this got me up and running. :+1:

**Comment by zenorocha** [comment]
Updated based on #3
